import '../models/medal.dart';

const List<Medal> kMedalCatalog = [
  Medal(
    id: 'first_checkin',
    title: 'First Transmission',
    description: 'Submit your first daily check-in.',
    category: 'Discipline',
    isUnlocked: false,
    unlockedAtDateKey: null,
    iconKey: 'radio',
  ),
  Medal(
    id: 'chain_3',
    title: 'Three-Day Chain',
    description: 'Hold a discipline chain for 3 days.',
    category: 'Discipline',
    isUnlocked: false,
    unlockedAtDateKey: null,
    iconKey: 'link',
  ),
  Medal(
    id: 'chain_7',
    title: 'Seven-Day Chain',
    description: 'Hold a discipline chain for 7 days.',
    category: 'Discipline',
    isUnlocked: false,
    unlockedAtDateKey: null,
    iconKey: 'chain7',
  ),
  Medal(
    id: 'chain_30',
    title: 'Thirty-Day Chain',
    description: 'Hold a discipline chain for 30 days.',
    category: 'Discipline',
    isUnlocked: false,
    unlockedAtDateKey: null,
    iconKey: 'chain30',
  ),
  Medal(
    id: 'first_protocol',
    title: 'Protocol Initiated',
    description: 'Finish a protocol with at least 25% effort.',
    category: 'Training',
    isUnlocked: false,
    unlockedAtDateKey: null,
    iconKey: 'play',
  ),
  Medal(
    id: 'perfect_protocol',
    title: 'Perfect Protocol',
    description: 'Complete a full protocol at 100% effort.',
    category: 'Training',
    isUnlocked: false,
    unlockedAtDateKey: null,
    iconKey: 'perfect',
  ),
  Medal(
    id: 'iron_resolve',
    title: 'Iron Resolve',
    description: 'Complete a protocol with low energy and 75% effort.',
    category: 'Training',
    isUnlocked: false,
    unlockedAtDateKey: null,
    iconKey: 'resolve',
  ),
  Medal(
    id: 'recovery_specialist',
    title: 'Recovery Specialist',
    description: 'Complete 3 recovery-lane sessions in a row.',
    category: 'Training',
    isUnlocked: false,
    unlockedAtDateKey: null,
    iconKey: 'recovery',
  ),
  Medal(
    id: 'first_promotion',
    title: 'Promotion Confirmed',
    description: 'Cross your first rank boundary.',
    category: 'Career',
    isUnlocked: false,
    unlockedAtDateKey: null,
    iconKey: 'promotion',
  ),
  Medal(
    id: 'promotion_5',
    title: 'Five Promotions',
    description: 'Log five promotions in your service record.',
    category: 'Career',
    isUnlocked: false,
    unlockedAtDateKey: null,
    iconKey: 'promotion5',
  ),
  Medal(
    id: 'elite_operator',
    title: 'Elite Operator',
    description: 'Reach the Elite Operator rank.',
    category: 'Career',
    isUnlocked: false,
    unlockedAtDateKey: null,
    iconKey: 'elite',
  ),
  Medal(
    id: 'weekly_objective_1',
    title: 'Weekly Commendation',
    description: 'Complete a weekly objective once.',
    category: 'Consistency',
    isUnlocked: false,
    unlockedAtDateKey: null,
    iconKey: 'calendar',
  ),
  Medal(
    id: 'weekly_protocol_4',
    title: 'Operational Week',
    description: 'Execute four protocols in a single week.',
    category: 'Consistency',
    isUnlocked: false,
    unlockedAtDateKey: null,
    iconKey: 'week4',
  ),
];
